services:
  - type: web
    name: kglppro-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://final-project-eta-umber.vercel.app
      - key: DATABASE
        sync: false
